a = Analysis(
	['scc/bin/sc_controller.py'],
	pathex=[],
	binaries=[],
	datas=[
		("glade/",  "glade/"),
		("images/", "images/"),
		("default_profiles/", "default_profiles/"),
		("default_menus/", "default_menus/"),
		("osd-styles/", "osd-styles/"),
		("gamecontrollerdb.txt", "."),
		# ("share/icons/hicolor/24x24/status", glob.glob("images/24x24/status/*.png")),
		# ("share/icons/hicolor/256x256/status", glob.glob("images/256x256/status/*.png")),
		# ("share/scc/", ["gamecontrollerdb.txt"]),
		# ("share/pixmaps", [ "images/sc-controller.svg" ]),
		# ("share/mime/packages", [ "scc-mime-types.xml" ]),
		# ("share/applications", ["scripts/sc-controller.desktop" ]),
		# ("lib/udev/rules.d", glob.glob("scripts/*.rules")),
	],
	hiddenimports=[
		"scc"
		"scc.bin",
		"scc.drivers",
		"scc.lib",
		"scc.x11",
		"scc.osd",
		"scc.foreign",
		"scc.gui",
		"scc.gui.app",
		"scc.gui.ae",
		"scc.gui.importexport",
		"scc.gui.creg",
	],
	hookspath=[],
	hooksconfig={},
	runtime_hooks=[],
	excludes=[],
	noarchive=False,
	optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
	pyz,
	a.scripts,
	[],
	exclude_binaries=True,
	name='sc_controller',
	debug=False,
	bootloader_ignore_signals=False,
	strip=False,
	upx=True,
	console=True,
	disable_windowed_traceback=False,
	argv_emulation=False,
	target_arch=None,
	codesign_identity=None,
	entitlements_file=None,
)
coll = COLLECT(
	exe,
	a.binaries,
	a.datas,
	strip=False,
	upx=True,
	upx_exclude=[],
	name='sc_controller',
)
