name: SCC Linux CI

on:
  push:
    branches:
      - main
      - master
      - python3
  pull_request:
    branches:
      - main
      - master
      - python3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      # Install dependencies
      - run: |
        apt install -y python3-setuptools
        pip install ioctl-opt libusb1 toml vdf pytest
      # Build
      - run: python -m build
      # Test
      - run: python -m pytest tests
