name: SCC Linux CI

on:
  push:
    branches:
      - main
      - master
      - python3
  pull_request:
    branches:
      - main
      - master
      - python3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      # TODO(Martin): Replace URL with just 'hidraw-pure' when https://github.com/vpelletier/python-hidraw/issues/7 is resolved
      - name: Install dependencies
        run: pip install build evdev setuptools https://github.com/C0rn3j/python-hidraw/archive/modernize.zip ioctl-opt libusb1 vdf pytest

      - name: Build SCC
        run: python -m build

      - name: Install SCC
        run: python -m pip install dist/*.whl

      - name: Run tests
        run: python -m pytest tests
